name: Jacopo is cool
favicon: null
layout_spectrum: 0.030154540669173002
typography_spectrum: 0.807159909280017
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.09270126884803176
  lightness: 0.5515713538043201
  saturation: 0.6423637848347425
  rhythmicContrast: 0.7085877293720841
purpose: []
